// <auto-generated />
using Bootcamp.Net.ENTITY.Exo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bootcamp.Net.ENTITY.Exo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250210112047_Relations")]
    partial class Relations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeSortie")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RealisateurId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RealisateurId");

                    b.HasIndex("Titre")
                        .IsUnique();

                    b.ToTable("Films", t =>
                        {
                            t.HasCheckConstraint("AnneeSortie", "AnneeSortie > 1975");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneeSortie = 1977,
                            Genre = "Science-Fiction",
                            RealisateurId = 10,
                            Titre = "Star Wars : Un nouvel espoir"
                        },
                        new
                        {
                            Id = 2,
                            AnneeSortie = 1980,
                            Genre = "Science-Fiction",
                            RealisateurId = 10,
                            Titre = "Star Wars : L'empire contre-attaque"
                        },
                        new
                        {
                            Id = 3,
                            AnneeSortie = 1983,
                            Genre = "Science-Fiction",
                            RealisateurId = 10,
                            Titre = "Star Wars : Le retour du Jedi"
                        },
                        new
                        {
                            Id = 4,
                            AnneeSortie = 2005,
                            Genre = "Société",
                            RealisateurId = 8,
                            Titre = "Hooligans"
                        },
                        new
                        {
                            Id = 5,
                            AnneeSortie = 2001,
                            Genre = "Heroic-Fantasy",
                            RealisateurId = 9,
                            Titre = "LOTR - La communauté de l'anneau"
                        },
                        new
                        {
                            Id = 6,
                            AnneeSortie = 2002,
                            Genre = "Heroic-Fantasy",
                            RealisateurId = 9,
                            Titre = "LOTR - Les deux tours"
                        },
                        new
                        {
                            Id = 7,
                            AnneeSortie = 2003,
                            Genre = "Heroic-Fantasy",
                            RealisateurId = 9,
                            Titre = "LOTR - Le retour du roi"
                        });
                });

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.FilmPersonne", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("PersonneId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "PersonneId");

                    b.HasIndex("PersonneId");

                    b.ToTable("FilmPersonnes");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            PersonneId = 3
                        },
                        new
                        {
                            FilmId = 1,
                            PersonneId = 4
                        },
                        new
                        {
                            FilmId = 1,
                            PersonneId = 5
                        },
                        new
                        {
                            FilmId = 2,
                            PersonneId = 3
                        },
                        new
                        {
                            FilmId = 2,
                            PersonneId = 4
                        },
                        new
                        {
                            FilmId = 2,
                            PersonneId = 5
                        },
                        new
                        {
                            FilmId = 3,
                            PersonneId = 3
                        },
                        new
                        {
                            FilmId = 3,
                            PersonneId = 4
                        },
                        new
                        {
                            FilmId = 3,
                            PersonneId = 5
                        },
                        new
                        {
                            FilmId = 4,
                            PersonneId = 1
                        },
                        new
                        {
                            FilmId = 4,
                            PersonneId = 2
                        },
                        new
                        {
                            FilmId = 5,
                            PersonneId = 1
                        },
                        new
                        {
                            FilmId = 5,
                            PersonneId = 6
                        },
                        new
                        {
                            FilmId = 5,
                            PersonneId = 7
                        },
                        new
                        {
                            FilmId = 6,
                            PersonneId = 1
                        },
                        new
                        {
                            FilmId = 6,
                            PersonneId = 6
                        },
                        new
                        {
                            FilmId = 6,
                            PersonneId = 7
                        },
                        new
                        {
                            FilmId = 7,
                            PersonneId = 1
                        },
                        new
                        {
                            FilmId = 7,
                            PersonneId = 6
                        },
                        new
                        {
                            FilmId = 7,
                            PersonneId = 7
                        });
                });

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Wood",
                            Prenom = "Elijah"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Hunnam",
                            Prenom = "Charlie"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Ford",
                            Prenom = "Harisson"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Hammil",
                            Prenom = "Mark"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Fisher",
                            Prenom = "Carrie"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Mortensen",
                            Prenom = "Vigo"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Bloom",
                            Prenom = "Orlando"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Alexander",
                            Prenom = "Lexi"
                        },
                        new
                        {
                            Id = 9,
                            Nom = "Jackson",
                            Prenom = "Peter"
                        },
                        new
                        {
                            Id = 10,
                            Nom = "Lucas",
                            Prenom = "Georges"
                        });
                });

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.Film", b =>
                {
                    b.HasOne("Bootcamp.Net.ENTITY.Exo.Entities.Personne", "Realisateur")
                        .WithMany("FilmReal")
                        .HasForeignKey("RealisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Realisateur");
                });

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.FilmPersonne", b =>
                {
                    b.HasOne("Bootcamp.Net.ENTITY.Exo.Entities.Film", "Film")
                        .WithMany("Acteurs")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bootcamp.Net.ENTITY.Exo.Entities.Personne", "Personne")
                        .WithMany("Roles")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.Film", b =>
                {
                    b.Navigation("Acteurs");
                });

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Exo.Entities.Personne", b =>
                {
                    b.Navigation("FilmReal");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
