// <auto-generated />
using System;
using Bootcamp.Net.ENTITY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bootcamp.Net.ENTITY.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250207082023_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bootcamp.Net.ENTITY.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<int>("PEGI")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Games", t =>
                        {
                            t.HasCheckConstraint("PEGI", "PEGI IN (3,7,12,16,18)");

                            t.HasCheckConstraint("Price", "Price > 0");

                            t.HasCheckConstraint("ReleaseDate", "ReleaseDate > '1958-10-18'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Premier jeu de la série Zelda.",
                            IsNew = false,
                            PEGI = 7,
                            Price = 49.99m,
                            ReleaseDate = new DateTime(1986, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Zelda"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Jeu de plateforme révolutionnaire.",
                            IsNew = false,
                            PEGI = 3,
                            Price = 39.99m,
                            ReleaseDate = new DateTime(1985, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Super Mario Bros."
                        },
                        new
                        {
                            Id = 3,
                            Description = "RPG en monde ouvert.",
                            IsNew = false,
                            PEGI = 18,
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "RPG futuriste immersif.",
                            IsNew = true,
                            PEGI = 18,
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Jeu en monde ouvert.",
                            IsNew = false,
                            PEGI = 18,
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 6,
                            Description = "RPG en monde ouvert légendaire.",
                            IsNew = false,
                            PEGI = 16,
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Skyrim"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Aventures historiques en Italie.",
                            IsNew = false,
                            PEGI = 18,
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2009, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed II"
                        },
                        new
                        {
                            Id = 8,
                            Description = "FPS en monde ouvert.",
                            IsNew = false,
                            PEGI = 18,
                            Price = 44.99m,
                            ReleaseDate = new DateTime(2012, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Far Cry 3"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Aventures western réalistes.",
                            IsNew = false,
                            PEGI = 18,
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Action et exploration en 3D.",
                            IsNew = false,
                            PEGI = 12,
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2002, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Metroid Prime"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Jeu de survie",
                            IsNew = true,
                            PEGI = 16,
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2013, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rust"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
